### ISSUE TITLE
Mixed up inputs for Procedural Noise and Procedural Cellular in the documentation

### ISSUE THREAD

**Issue by baharmon** [interopxyz/BitmapPlus#3]
Some of the inputs for [Procedural Noise](https://interopxyz.gitbook.io/bitmap-plus/components/create/procedural-noise) and [Procedural Cellular](https://interopxyz.gitbook.io/bitmap-plus/components/create/procedural-cellular) are mixed up in the GitBook documentation. Both have *Boundary Mode* and *Interpolation Mode*,  when Procedural Noise should have *Mode* and *Interpolation*. Procedural Cellular has the wrong options for *Boundary Mode* and *Interpolation Mode*, e.g. value, Perlin, cubic, simplex, etc.

**Comment by interopxyz** [comment]
Thank's for the notification on this.
The documentation has been updated.
